# Generated by Django 5.2.17 on 2026-09-10 10:29

import django.core.validators
from django.db import migrations, models


def seed_random_indices(apps, schema_editor):
    random_index = apps.get_model("ahp", "RandomIndex")
    values = {
        1: "0.0000", 2: "0.0000", 3: "0.5800", 4: "0.9000",
        5: "1.1200", 6: "1.2400", 7: "1.3200", 8: "1.4100",
        9: "1.4500", 10: "1.4900", 11: "1.5100", 12: "1.4800",
        13: "1.5600", 14: "1.5700", 15: "1.5900",
    }
    for matrix_size, value in values.items():
        random_index.objects.get_or_create(
            matrix_size=matrix_size,
            defaults={"value": value, "source": "Tabela RI de Saaty"},
        )


def remove_random_indices(apps, schema_editor):
    apps.get_model("ahp", "RandomIndex").objects.all().delete()


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RandomIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matrix_size', models.PositiveSmallIntegerField(unique=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Ordem da matriz (n)')),
                ('value', models.DecimalField(decimal_places=4, max_digits=8, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Índice aleatório (RI)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('source', models.CharField(blank=True, max_length=160, verbose_name='Fonte/observação')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Índice aleatório (RI)',
                'verbose_name_plural': 'Tabela de índices aleatórios (RI)',
                'ordering': ['matrix_size'],
            },
        ),
        migrations.RunPython(seed_random_indices, remove_random_indices),
    ]
