# Generated by Django 5.2.17 on 2026-09-01 14:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Criterion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, verbose_name='Código')),
                ('name', models.CharField(max_length=160, verbose_name='Nome')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('kind', models.CharField(choices=[('BENEFIT', 'Benefício (maior é melhor)'), ('COST', 'Custo (menor é melhor)')], default='BENEFIT', max_length=16, verbose_name='Tipo')),
                ('catalog_weight', models.DecimalField(blank=True, decimal_places=4, help_text='Peso informativo no catálogo. O peso da decisão é calculado pelo AHP.', max_digits=8, null=True, verbose_name='Peso de catálogo (opcional)')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Ativo')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='criteria.criterion', verbose_name='Critério pai')),
            ],
            options={
                'verbose_name': 'Critério',
                'verbose_name_plural': 'Critérios',
                'ordering': ['sort_order', 'code'],
                'indexes': [models.Index(fields=['is_active', 'parent'], name='criteria_cr_is_acti_2577fd_idx')],
                'constraints': [models.UniqueConstraint(fields=('code', 'parent'), name='uniq_criterion_code_per_parent')],
            },
        ),
    ]
