# Generated by Django 5.2.17 on 2026-09-01 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EngineeringService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome')),
                ('service_type', models.CharField(choices=[('HVAC', 'Ar condicionado/HVAC'), ('ELECTRICAL', 'Rede elétrica'), ('HOSPITAL', 'Equipamentos hospitalares'), ('DATA_NETWORK', 'Rede de dados'), ('BUILDING', 'Manutenção predial'), ('OTHER', 'Outros')], db_index=True, max_length=20, verbose_name='Tipo de serviço')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('location', models.CharField(blank=True, max_length=180, verbose_name='Local')),
                ('priority', models.CharField(choices=[('LOW', 'Baixa'), ('MEDIUM', 'Média'), ('HIGH', 'Alta'), ('CRITICAL', 'Crítica')], default='MEDIUM', max_length=16, verbose_name='Prioridade')),
                ('requested_at', models.DateField(verbose_name='Data da solicitação')),
                ('deadline', models.DateField(blank=True, null=True, verbose_name='Prazo')),
                ('status', models.CharField(choices=[('OPEN', 'Aberto'), ('IN_PROGRESS', 'Em curso'), ('CLOSED', 'Encerrado'), ('CANCELLED', 'Cancelado')], db_index=True, default='OPEN', max_length=16, verbose_name='Estado')),
                ('is_demo', models.BooleanField(default=False, verbose_name='Dados de demonstração')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Serviço de engenharia',
                'verbose_name_plural': 'Serviços de engenharia',
                'ordering': ['-requested_at', 'name'],
                'indexes': [models.Index(fields=['name'], name='services_en_name_2fb5c2_idx')],
            },
        ),
    ]
