# Generated by Django 5.2.17 on 2026-09-01 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180, verbose_name='Nome da empresa')),
                ('nuit', models.CharField(max_length=20, unique=True, verbose_name='NUIT')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(max_length=30, verbose_name='Telefone')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Endereço')),
                ('city', models.CharField(blank=True, max_length=80, verbose_name='Cidade')),
                ('province', models.CharField(blank=True, max_length=80, verbose_name='Província')),
                ('contact_person', models.CharField(blank=True, max_length=120, verbose_name='Responsável')),
                ('specialties', models.TextField(blank=True, verbose_name='Especialidades')),
                ('experience_years', models.PositiveIntegerField(default=0, verbose_name='Anos de experiência')),
                ('certifications', models.TextField(blank=True, verbose_name='Certificações')),
                ('status', models.CharField(choices=[('ACTIVE', 'Ativo'), ('INACTIVE', 'Inativo')], db_index=True, default='ACTIVE', max_length=16, verbose_name='Estado')),
                ('is_demo', models.BooleanField(default=False, verbose_name='Dados de demonstração')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Fornecedor',
                'verbose_name_plural': 'Fornecedores',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='suppliers_s_name_6277a9_idx'), models.Index(fields=['status', 'name'], name='suppliers_s_status_3f308a_idx')],
            },
        ),
    ]
