# Generated by Django 5.2.17 on 2026-09-01 14:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('criteria', '0001_initial'),
        ('services', '0001_initial'),
        ('suppliers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objective', models.CharField(default='Selecionar o melhor fornecedor para o serviço de engenharia', max_length=255, verbose_name='Objetivo')),
                ('notes', models.TextField(blank=True, verbose_name='Observações')),
                ('status', models.CharField(choices=[('DRAFT', 'Rascunho'), ('IN_PROGRESS', 'Em avaliação'), ('INCONSISTENT', 'Inconsistente'), ('COMPLETED', 'Concluída'), ('CANCELLED', 'Cancelada')], db_index=True, default='DRAFT', max_length=16, verbose_name='Estado')),
                ('current_step', models.PositiveSmallIntegerField(default=1, verbose_name='Passo do assistente')),
                ('allow_inconsistent_completion', models.BooleanField(default=False, help_text='Apenas administrador pode ativar.', verbose_name='Permitir conclusão com inconsistência')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Concluída em')),
                ('is_demo', models.BooleanField(default=False, verbose_name='Dados de demonstração')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('evaluator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evaluations', to=settings.AUTH_USER_MODEL, verbose_name='Avaliador')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evaluations', to='services.engineeringservice', verbose_name='Serviço')),
            ],
            options={
                'verbose_name': 'Avaliação',
                'verbose_name_plural': 'Avaliações',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AHPResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('worst_cr', models.DecimalField(decimal_places=6, max_digits=12)),
                ('all_consistent', models.BooleanField(default=False)),
                ('explanations', models.JSONField(default=list)),
                ('payload', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('evaluation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ahp_result', to='evaluations.evaluation')),
            ],
            options={
                'verbose_name': 'Resultado AHP',
            },
        ),
        migrations.CreateModel(
            name='EvaluationCriterion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot_code', models.CharField(max_length=20)),
                ('snapshot_name', models.CharField(max_length=160)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('criterion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='criteria.criterion')),
                ('evaluation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluation_criteria', to='evaluations.evaluation')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='evaluations.evaluationcriterion')),
            ],
            options={
                'verbose_name': 'Critério da avaliação',
                'ordering': ['snapshot_code'],
            },
        ),
        migrations.CreateModel(
            name='CriterionWeight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local_weight', models.DecimalField(decimal_places=6, max_digits=12)),
                ('global_weight', models.DecimalField(decimal_places=6, max_digits=12)),
                ('is_leaf', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('evaluation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criterion_weights', to='evaluations.evaluation')),
                ('evaluation_criterion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weights', to='evaluations.evaluationcriterion')),
            ],
            options={
                'verbose_name': 'Peso de critério',
            },
        ),
        migrations.CreateModel(
            name='ComparisonMatrix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matrix_type', models.CharField(choices=[('CRITERIA', 'Critérios'), ('SUBCRITERIA', 'Subcritérios'), ('ALTERNATIVES', 'Alternativas')], max_length=16)),
                ('labels', models.JSONField(default=list)),
                ('matrix', models.JSONField(default=list)),
                ('normalized_matrix', models.JSONField(default=list)),
                ('lambda_max', models.DecimalField(decimal_places=6, max_digits=12, null=True)),
                ('ci', models.DecimalField(decimal_places=6, max_digits=12, null=True)),
                ('ri', models.DecimalField(decimal_places=4, max_digits=8, null=True)),
                ('cr', models.DecimalField(decimal_places=6, max_digits=12, null=True)),
                ('is_consistent', models.BooleanField(default=False)),
                ('interpretation', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('evaluation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matrices', to='evaluations.evaluation')),
                ('parent_criterion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='evaluations.evaluationcriterion')),
            ],
            options={
                'verbose_name': 'Matriz de comparação',
            },
        ),
        migrations.CreateModel(
            name='EvaluationSupplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot_name', models.CharField(max_length=180)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('evaluation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluation_suppliers', to='evaluations.evaluation')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='suppliers.supplier')),
            ],
            options={
                'verbose_name': 'Fornecedor da avaliação',
                'ordering': ['snapshot_name'],
            },
        ),
        migrations.CreateModel(
            name='AlternativePriority',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local_priority', models.DecimalField(decimal_places=6, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('evaluation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alternative_priorities', to='evaluations.evaluation')),
                ('evaluation_criterion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alternative_priorities', to='evaluations.evaluationcriterion')),
                ('evaluation_supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='priorities', to='evaluations.evaluationsupplier')),
            ],
            options={
                'verbose_name': 'Prioridade local',
            },
        ),
        migrations.CreateModel(
            name='PairwiseComparison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matrix_type', models.CharField(choices=[('CRITERIA', 'Critérios'), ('SUBCRITERIA', 'Subcritérios'), ('ALTERNATIVES', 'Alternativas')], max_length=16)),
                ('preferred', models.CharField(choices=[('LEFT', 'Esquerda'), ('RIGHT', 'Direita'), ('EQUAL', 'Iguais')], max_length=8)),
                ('intensity', models.PositiveSmallIntegerField()),
                ('value', models.DecimalField(decimal_places=6, help_text='a_left,right na escala de Saaty (recíproco implícito).', max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('evaluation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comparisons', to='evaluations.evaluation')),
                ('left_criterion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='as_left_criterion', to='evaluations.evaluationcriterion')),
                ('left_supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='as_left_supplier', to='evaluations.evaluationsupplier')),
                ('parent_criterion', models.ForeignKey(blank=True, help_text='Pai dos subcritérios ou critério-folha das alternativas.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_comparisons', to='evaluations.evaluationcriterion')),
                ('right_criterion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='as_right_criterion', to='evaluations.evaluationcriterion')),
                ('right_supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='as_right_supplier', to='evaluations.evaluationsupplier')),
            ],
            options={
                'verbose_name': 'Comparação pareada',
            },
        ),
        migrations.CreateModel(
            name='Ranking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField()),
                ('global_priority', models.DecimalField(decimal_places=6, max_digits=12)),
                ('percent', models.DecimalField(decimal_places=2, max_digits=8)),
                ('is_recommended', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('evaluation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rankings', to='evaluations.evaluation')),
                ('evaluation_supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rankings', to='evaluations.evaluationsupplier')),
            ],
            options={
                'verbose_name': 'Ranking',
                'ordering': ['position'],
            },
        ),
        migrations.AddIndex(
            model_name='evaluation',
            index=models.Index(fields=['status', 'created_at'], name='evaluations_status_1044bd_idx'),
        ),
        migrations.AddIndex(
            model_name='evaluation',
            index=models.Index(fields=['evaluator', 'status'], name='evaluations_evaluat_93318f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='evaluationcriterion',
            unique_together={('evaluation', 'criterion')},
        ),
        migrations.AlterUniqueTogether(
            name='criterionweight',
            unique_together={('evaluation', 'evaluation_criterion')},
        ),
        migrations.AlterUniqueTogether(
            name='comparisonmatrix',
            unique_together={('evaluation', 'matrix_type', 'parent_criterion')},
        ),
        migrations.AlterUniqueTogether(
            name='evaluationsupplier',
            unique_together={('evaluation', 'supplier')},
        ),
        migrations.AlterUniqueTogether(
            name='alternativepriority',
            unique_together={('evaluation', 'evaluation_supplier', 'evaluation_criterion')},
        ),
        migrations.AddIndex(
            model_name='pairwisecomparison',
            index=models.Index(fields=['evaluation', 'matrix_type'], name='evaluations_evaluat_dbf874_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='ranking',
            unique_together={('evaluation', 'evaluation_supplier')},
        ),
    ]
