# Generated by Django 5.2.17 on 2026-09-10 10:29

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProposalAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='proposals/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'xls', 'xlsx', 'png', 'jpg', 'jpeg'])], verbose_name='Ficheiro')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Descrição')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('evaluation_supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposal_attachments', to='evaluations.evaluationsupplier', verbose_name='Fornecedor da avaliação')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_proposals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Anexo de proposta',
                'verbose_name_plural': 'Anexos de propostas',
                'ordering': ['-created_at'],
            },
        ),
    ]
